name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
        cache: 'maven'
    - run: mvn verify
    - uses: actions/upload-artifact@v2
      with:
        name: menu-server
        path: target/menu-server.jar
  release:
    runs-on: ubuntu-20.04
    needs: build
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.jar